### ISSUE TITLE
File name is not displayed

### ISSUE THREAD

**Issue by eitsupi** [quarto-ext/code-filename#2]
Thanks for the great extension. This is very useful.

I immediately tried this in the following location, but for some reason the file name does not seem to show up in this project.
https://github.com/rocker-org/website/blob/e10a3d05bf145bc8ba3a924ac82e8d3d315143ac/use/networking.md?plain=1#L33-L35

````md
```{.default filename="Renviron"}
ALL_PROXY=http://192.168.1.12:3128
```
````

![image](https://user-images.githubusercontent.com/50911393/178274756-8b44e28a-3680-4b69-96fe-48544a52dde0.png)

If I read the HTML, it contains `data-filename="Renviron"`, so perhaps the CSS is not being applied correctly?

**Comment by eitsupi** [comment]
> Did you activate it using
> 
> ```yaml
> filters: 
>   - code-filename
> ```
> 
> like you would do for a custom filter ?

Sorry, I thought I had tried it, but I typo'd `filter` instead of `filters`.

The correct configuration resulted in the following display and the following log for the `quarto preview` command.

![image](https://user-images.githubusercontent.com/50911393/178295854-f31a879c-34a2-43cc-a21d-7b199d4aa449.png)

```
/site_libs/code-filename-0.0.1/code-filename.css (404: Not Found)
```

**Comment by eitsupi** [comment]
> Do you have latest quarto version and extension version ?

Yes, quarto v1.0.8 and the latest extension.

**Comment by eitsupi** [comment]
It seems to work correctly in the `index.md`.
There may be an error when used on files in subdirectories.

**Comment by eitsupi** [comment]
@cderv The local preview went well, so I pushed it to GitHub and it failed to build.
And this seems to reproduce locally as well (with the `quarto render` command).
It looks like sometimes the filter runs well and sometimes it doesn't......

https://github.com/rocker-org/website/runs/7285754121?check_suite_focus=true#step:4:24

![image](https://user-images.githubusercontent.com/50911393/178304710-1c29d31a-5b7a-4ea7-88d2-0d2a919604ce.png)

**Comment by cderv** [comment]
Are you installing the extension in your CI build process ? Or are you committing the local extension to git so that it is available in the project at render time?

**Comment by eitsupi** [comment]
> Are you installing the extension in your CI build process ? Or are you committing the local extension to git so that it is available in the project at render time?

https://github.com/rocker-org/website/tree/ce40f1b7be0a99759bc73d23a993a25c182f1a71

The extension is committed to the repository and CI is just running `quarto render` as in the following yml file.

```yml
jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v3
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/install-quarto@v1
        with:
          version: "1.0.8"
      - name: Build
        run: quarto render
```
